# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.11.0
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-resource.com
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: true
plot_dependencies: false
project_description_short: Global Climate Assessment of Global Emission Scenarios,
    typically (but not always) produced by Integrated Assessment Models (IAMs).
project_name_human: gcages
project_name_pip: gcages
project_name_python: gcages
project_url: https://github.com/openscm/gcages
track_lock_file: true
